### ISSUE TITLE
How to use or configure this extension? 如何使用或配置该扩展？

### ISSUE THREAD

**Issue by TheVeryDarkness** [pengweiqhca/TransparencyTheme#1]
I've installed this on VS2022 Preview, but nothing seems to happen, I wonder if I missed some configuration. And if so, how to configure it?
我已经在VS2022预览版上安装了这个扩展，但是看起来无事发生，我怀疑是缺少了什么配置，如果是这样的话，请问该如何配置？

**Comment by pengweiqhca** [comment]
You need select `Transparency` theme in tool > environment > general. amd you need install [ClaudiaIDE](https://marketplace.visualstudio.com/items?itemName=kbuchi.ClaudiaIDE)
